-- DAY 1 / 100 REAL BUSINESS QUESTIONS  
CREATE TABLE sales_data (
    sale_id SERIAL PRIMARY KEY,
    product_name VARCHAR(50),
    category VARCHAR(50),
    sale_date DATE,
    quantity INT,
    unit_price DECIMAL(10, 2)
);

INSERT INTO sales_data (product_name, category, sale_date, quantity, unit_price) VALUES
('Notebook', 'Stationery', '2024-01-05', 10, 50.00),
('Pen', 'Stationery', '2024-01-06', 20, 10.00),
('Pencil', 'Stationery', '2024-01-07', 15, 5.00),
('Marker', 'Stationery', '2024-01-08', 5, 20.00),
('Desk Chair', 'Furniture', '2024-01-10', 2, 1500.00),
('Table', 'Furniture', '2024-01-12', 1, 3000.00),
('Notebook', 'Stationery', '2024-01-15', 8, 50.00),
('Pen', 'Stationery', '2024-01-16', 25, 10.00),
('Desk Chair', 'Furniture', '2024-01-20', 1, 1500.00);

SELECT * FROM SALES_DATA;

-- Q: As a sales analyst, identify the total revenue generated by each region in January 2024. Sort the results from highest to lowest revenue.

SELECT
	REGION,
	SUM(QUANTITY * UNIT_PRICE) AS TOTAL_REVENUE
FROM
	SALES_DATA
WHERE
	SALE_DATE BETWEEN '2024-01-01' AND '2024-01-31'
GROUP BY
	REGION
ORDER BY
	TOTAL_REVENUE DESC;
